### ISSUE TITLE
Unexpected error on uninitialized object attributes with possible value of undefined

### ISSUE THREAD

**Issue by davemneo** [neo-one-suite/neo-one#1046] opened 2019-02-06 22:06 UTC
### Description

If a given Mix-in adds new attributes declared as  ` aTYPE | undefined; ` initial usage throws VM Error.
 
### Steps to Reproduce

SmartContract MixIn that defines 
```
    private mutableOwner: Address | undefined; 
```
When this object attribute *not* assigned as default in the constructor, but when used later:

```
 > 42 |       if (this.mutableOwner === undefined) {
                                   ^
 Error [INVOKE]: VM Error: Invalid Value. Expected MapStackItem
```

**Expected behavior:** attribute should be ready to use w/o constructor assignment, expected value is ` undefined `;

**Actual behavior:** VM Error

**Reproduces how often:**  100%

Workaround: assign `  undefined  ` value in constructor

**Comment by dicarlo2** [comment] 2019-04-23 18:00
Duplicate of https://github.com/neo-one-suite/neo-one/issues/1342

**Closed by dicarlo2** 2019-04-23 18:00 UTC
Labels: [zube]: Ready
