### ISSUE TITLE
Additional Options to SmartContract's calls not throwing appropriate type-error.

### ISSUE THREAD

**Issue by davemneo** [neo-one-suite/neo-one#1048] opened 2019-02-06 22:38 UTC
### Description

```typescript
        const initTransferResult = await smartContract.transferContract(
          {
            from: publisher.userAccount.id.address,
            to: recipient.userAccount.id.address,
          },
          { from: masterAccountID.address },
        );
```
This should throw inline type-errors on the second argument of  ` from: masterAccountID.address ` because  ` from: masterAccountID ` is expected.

**Comment by dicarlo2** [comment] 2019-04-23 18:01
Duplicate of https://github.com/neo-one-suite/neo-one/issues/1047

**Closed by dicarlo2** 2019-04-23 18:01 UTC
Labels: [zube]: Ready
